package com.hexaware.entity;

import java.util.Date;
import java.util.List;

public class Orders {
    private int orderId;
    private int userId;
    private Date orderDate;
    
    private List<OrderItem> items;

    public Orders(int orderId, int userId, Date orderDate, List<OrderItem> items) {
        this.orderId = orderId;
        this.userId = userId;
        this.orderDate = orderDate;
        
        this.items = items;
    }

    // Optional: constructor without orderId if it's auto-generated by the DB
    public Orders(int userId, Date orderDate,  List<OrderItem> items) {
        this.userId = userId;
        this.orderDate = orderDate;
        
        this.items = items;
    }

    // Getters and setters
    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

  

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }
}
